import {
  Typography,
  Box,
  Container,
  Paper,
  Grid2,
  Button,
} from "@mui/material";
import {
  Timeline,
  TimelineItem,
  TimelineSeparator,
  TimelineConnector,
  TimelineContent,
  TimelineDot,
  timelineItemClasses,
} from "@mui/lab";

import { motion } from "framer-motion";
import DownloadIcon from "@mui/icons-material/Download";

const fadeIn = {
  initial: { opacity: 0, y: 20 },
  animate: { opacity: 1, y: 0 },
  transition: { duration: 0.5 },
};

export default function Resume() {
  return (
    <Container>
      <motion.div initial="initial" animate="animate" variants={fadeIn}>
        <Box sx={{ py: 4 }}>
          <Box
            sx={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              mb: 4,
            }}
          >
            <Typography variant="h3" component="h1">
              Resume
            </Typography>
            <Button
              variant="contained"
              startIcon={<DownloadIcon />}
              href="/resume.pdf"
              target="_blank"
            >
              Download PDF
            </Button>
          </Box>

          <Grid2 container spacing={4}>
            <Grid2 size={{ xs: 12, sm: 8 }}>
              <Paper sx={{ p: 3, mb: 3 }}>
                <Typography variant="h5" gutterBottom>
                  Work Experience
                </Typography>
                <Timeline
                  position="right"
                  sx={{
                    [`& .${timelineItemClasses.root}:before`]: {
                      flex: 0,
                      padding: 0,
                    },
                  }}
                >
                  <TimelineItem>
                    <TimelineSeparator>
                      <TimelineDot color="primary" />
                      <TimelineConnector />
                    </TimelineSeparator>
                    <TimelineContent>
                      <Typography variant="h6">Outlier.ai</Typography>
                      <Typography variant="subtitle2" color="text.secondary">
                        Freelance AI Prompt Engineer & Code Reviewer • Jan 2024
                        – Present
                      </Typography>
                      <Typography variant="body2" sx={{ mt: 1 }}>
                        • Enhanced code accuracy by analyzing and reviewing code
                        generated by LLMs in Python (including NumPy, Pandas,
                        and Matplotlib), JavaScript, Java, React, and C++.
                        <br />• Created challenging prompts to induce defects in
                        LLM-generated code, providing RLHF to new LLMs, ensuring
                        model improvements and customer satisfaction.
                        <br />• Leveraged prompt engineering to increase the
                        technical correctness of code generated by up to 30%.
                      </Typography>
                    </TimelineContent>
                  </TimelineItem>
                  <TimelineItem>
                    <TimelineSeparator>
                      <TimelineDot color="primary" />
                      <TimelineConnector />
                    </TimelineSeparator>
                    <TimelineContent>
                      <Typography variant="h6">
                        Warner Brothers Discovery (Formerly Discovery)
                      </Typography>
                      <Typography variant="subtitle2" color="text.secondary">
                        Software Development Engineer I & II • Nov 2019 – Aug
                        2022
                      </Typography>
                      <Typography variant="body2" sx={{ mt: 1 }}>
                        • Helped write the 0-to-1 metadata ingestion pipeline
                        for the first iteration of Discovery’s D2C video
                        delivery platform using TypeScript, and PostgreSQL on
                        AWS, using Pulumi for IaC and Jest for unit, functional,
                        and e2e tests.
                        <br />• Converted to a highly scalable
                        microservice-based architecture written in Golang which
                        supported 25+ regions of Discovery+ with a highly
                        redundant, fault-tolerant data pipeline for new content
                        ingestion.
                        <br />• Improved code quality and test coverage by
                        championing a test-driven development in new feature
                        work.
                        <br />• Became subject matter expert in Rollups service;
                        Simplifying operations and optimizing PostgreSQL queries
                        to reduce execution time by 10x from 15 minutes to ~90
                        seconds.
                        <br />• Improved operational excellence by designing and
                        creating episode re-parenting API, reducing support
                        tickets by 30%.
                        <br />• Worked with cross-functional teams around the
                        globe to support content ingestion issues surrounding
                        our API, in addition to troubleshooting, debugging, and
                        deploying services to Kubernetes as part of on-call
                        rotation.
                      </Typography>
                    </TimelineContent>
                  </TimelineItem>
                  <TimelineItem>
                    <TimelineSeparator>
                      <TimelineDot color="primary" />
                      <TimelineConnector />
                    </TimelineSeparator>
                    <TimelineContent>
                      <Typography variant="h6">Infoblox</Typography>
                      <Typography variant="subtitle2" color="text.secondary">
                        Software Engineer • Sep 2018 – Nov 2019
                      </Typography>
                      <Typography variant="body2" sx={{ mt: 1 }}>
                        • Implemented Okta SSO authentication service with JWTs
                        in Golang with Redis cache, improving security and
                        reducing authentication time by 20% over legacy Ruby on
                        Rails code.
                        <br />• Improved customer account API response time by
                        300% by optimizing SQL queries and migrating from Ruby
                        to a Golang microservice, including Docker for
                        containerization and Kubernetes for orchestration.
                        <br />• Improved click-through rate by 20% by
                        redesigning HTML email templates and associated
                        controllers in Ruby on Rails to add more
                        customer-specific data and enhance readability.
                        <br />• Created, managed, and participated in on-call
                        rotations for mission-critical systems (including
                        authentication service) leveraging PagerDuty and custom
                        metrics for alerts.
                      </Typography>
                    </TimelineContent>
                  </TimelineItem>
                  <TimelineItem>
                    <TimelineSeparator>
                      <TimelineDot color="primary" />
                      <TimelineConnector />
                    </TimelineSeparator>
                    <TimelineContent>
                      <Typography variant="h6">Infoblox</Typography>
                      <Typography variant="subtitle2" color="text.secondary">
                        Software Test Engineer • Sep 2017 – Sep 2018
                      </Typography>
                      <Typography variant="body2" sx={{ mt: 1 }}>
                        • Increased automated test coverage from 0% to 90% by
                        creating automated end-to-end tests for RPZ content
                        delivery system using PyTest, Jenkins, and Python.
                        <br />• Created a CI/CD pipeline in Jenkins using
                        Selenium and PyTest to reduce UI bugs by 50%.
                        <br />• Performed load testing via AWS Lambda to
                        simulate 10k concurrent connections to RPZ content
                        delivery service.
                        <br />• Boosted GUI test coverage from 0% to 40% by
                        designing GUI tests with PyTest and Selenium WebDriver.
                        <br />• Worked with customer support teams to quickly
                        triage and address system issues, and drive effective
                        cross-functional collaboration between support engineers
                        and developers for timely bug resolution.
                        <br />• Learned manual Kubernetes deployments and
                        administration (and later Helm charts and AWS
                        CloudFormation) to help assist the DevOps team as needed
                        with infrastructure improvements.
                      </Typography>
                    </TimelineContent>
                  </TimelineItem>
                  {/* Add more work experience items */}
                </Timeline>
              </Paper>

              <Paper sx={{ p: 3 }}>
                <Typography variant="h5" gutterBottom>
                  Education
                </Typography>
                <Timeline
                  position="right"
                  sx={{
                    [`& .${timelineItemClasses.root}:before`]: {
                      flex: 0,
                      padding: 0,
                    },
                  }}
                >
                  <TimelineItem>
                    <TimelineSeparator>
                      <TimelineDot color="primary" />
                      <TimelineConnector />
                    </TimelineSeparator>
                    <TimelineContent>
                      <Typography variant="h6">
                        University of Washington
                      </Typography>
                      <Typography variant="subtitle2" color="text.secondary">
                        Bachelor of Science in Computer Science & Systems • June
                        2017
                      </Typography>
                      <Typography variant="body2" sx={{ mt: 1 }}>
                        <b>Relevant Coursework:</b> Data Structures &
                        Algorithms; Compilers; Mobile App Development; Advanced
                        Programming Principles in Java, Python, C, Prolog, and
                        R; Computational Photography; Artificial Intelligence &
                        Machine Learning
                      </Typography>
                    </TimelineContent>
                  </TimelineItem>
                  {/* Add more education items */}
                </Timeline>
              </Paper>
            </Grid2>

            <Grid2 size={{ xs: 4, md: 3 }}>
              <Paper sx={{ p: 3, mb: 3 }}>
                <Typography variant="h5" gutterBottom>
                  Skills
                </Typography>
                <Typography variant="subtitle1" gutterBottom>
                  Technical Skills
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Golang <br />
                  Typescript <br />
                  Python <br />
                  React
                  <br />
                  SQL
                  <br />
                  PostgreSQL
                  <br />
                  AWS (EC2, RDS, Lambda, S3, SQS, etc.)
                  <br />
                </Typography>
                <Typography variant="subtitle1" gutterBottom sx={{ mt: 2 }}>
                  Soft Skills
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  Cross-Functional Collaboration <br />
                  Communication Across Distributed Teams <br />
                  Problem Solving <br />
                  Time Management <br />
                  Leadership <br />
                  Growth Mindset
                  <br />
                </Typography>
                <Typography variant="subtitle1" gutterBottom sx={{ mt: 2 }}>
                  Languages
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  English: Native Proficiency <br />
                  Japanese: Intermediate Proficiency <br />
                  Spanish: Elementary Proficiency <br />
                  Tagalog: Basic Proficiency <br />
                </Typography>
              </Paper>

              <Paper sx={{ p: 3 }}>
                <Typography variant="h5" gutterBottom>
                  Certifications
                </Typography>
                <Typography variant="body2" color="text.secondary">
                  CompTIA A+ <br />
                  TestOut PC Pro <br />
                  TestOut Network Pro
                </Typography>
              </Paper>
            </Grid2>
          </Grid2>
        </Box>
      </motion.div>
    </Container>
  );
}
