export interface Experience {
  company: string;
  title: string;
  date: string;
  description: string[]; // Array of bullet points
}

export interface Education {
  institution: string;
  degree: string;
  date: string;
  coursework?: string;
  githubRepo?: {
    text: string;
    url: string;
  };
  description?: string[]; // Array of bullet points for courses/achievements
}

export interface SkillCategory {
  category: string;
  skills: string[];
}

export interface Language {
  name: string;
  proficiency: string;
}

export interface Certification {
  name: string;
}

export interface ResumeData {
  workExperience: Experience[];
  education: Education[];
  technicalSkills: SkillCategory;
  softSkills: SkillCategory;
  languages: Language[];
  certifications: Certification[];
}

export const resumeData: ResumeData = {
  workExperience: [
    {
      company: "Appraisal Bureau",
      title: "Senior Full Stack Software Engineer",
      date: "Mar 2025 – Nov 2025",
      description: [
        "Successfully launched Appraisal Bureau progressive web app for managing fine artwork inventory, leveraging Strapi for content management and Stripe for payment solutions, written with Typescript, Next.js and React",
        "Added support for charitable artwork donations, owning feature end-to-end and complying with IRS regulations",
        "Built high-throughput media upload service using AWS S3 and Lambda to eliminate timeout errors",
        "Created unit, functional, and integration tests in Jest, and added automated UI test coverage with Cypress",
      ],
    },
    {
      company: "Outlier.ai",
      title: "Freelance AI Prompt Engineer & Code Reviewer",
      date: "Jan 2024 – Present",
      description: [
        "Enhanced code accuracy by analyzing and reviewing code generated by LLMs in Python (including NumPy, Pandas, and Matplotlib), JavaScript, Java, React, and C++.",
        "Created challenging prompts to induce defects in LLM-generated code, providing RLHF to new LLMs, ensuring model improvements and customer satisfaction.",
        "Leveraged prompt engineering to increase the technical correctness of code generated by up to 30%.",
      ],
    },
    {
      company: "Warner Brothers Discovery (Formerly Discovery)",
      title: "Software Development Engineer I & II",
      date: "Nov 2019 – Aug 2022",
      description: [
        "Helped write the 0-to-1 metadata ingestion pipeline for the first iteration of Discovery’s D2C video delivery platform using TypeScript, and PostgreSQL on AWS, using Pulumi for IaC and Jest for unit, functional, and e2e tests.",
        "Converted to a highly scalable microservice-based architecture written in Golang which supported 25+ regions of Discovery+ with a highly redundant, fault-tolerant data pipeline for new content ingestion.",
        "Improved code quality and test coverage by championing a test-driven development in new feature work.",
        "Became subject matter expert in Rollups service; Simplifying operations and optimizing PostgreSQL queries to reduce execution time by 10x from 15 minutes to ~90 seconds.",
        "Improved operational excellence by designing and creating episode re-parenting API, reducing support tickets by 30%.",
        "Worked with cross-functional teams around the globe to support content ingestion issues surrounding our API, in addition to troubleshooting, debugging, and deploying services to Kubernetes as part of on-call rotation.",
      ],
    },
    {
      company: "Infoblox",
      title: "Software Engineer",
      date: "Sep 2018 – Nov 2019",
      description: [
        "Implemented Okta SSO authentication service with JWTs in Golang with Redis cache, improving security and reducing authentication time by 20% over legacy Ruby on Rails code.",
        "Improved customer account API response time by 300% by optimizing SQL queries and migrating from Ruby to a Golang microservice, including Docker for containerization and Kubernetes for orchestration.",
        "Improved click-through rate by 20% by redesigning HTML email templates and associated controllers in Ruby on Rails to add more customer-specific data and enhance readability.",
        "Created, managed, and participated in on-call rotations for mission-critical systems (including authentication service) leveraging PagerDuty and custom metrics for alerts.",
      ],
    },
    {
      company: "Infoblox",
      title: "Software Test Engineer",
      date: "Sep 2017 – Sep 2018",
      description: [
        "Increased automated test coverage from 0% to 90% by creating automated end-to-end tests for RPZ content delivery system using PyTest, Jenkins, and Python.",
        "Created a CI/CD pipeline in Jenkins using Selenium and PyTest to reduce UI bugs by 50%.",
        "Performed load testing via AWS Lambda to simulate 10k concurrent connections to RPZ content delivery service.",
        "Boosted GUI test coverage from 0% to 40% by designing GUI tests with PyTest and Selenium WebDriver.",
        "Worked with customer support teams to quickly triage and address system issues, and drive effective cross-functional collaboration between support engineers and developers for timely bug resolution.",
        "Learned manual Kubernetes deployments and administration (and later Helm charts and AWS CloudFormation) to help assist the DevOps team as needed with infrastructure improvements.",
      ],
    },
  ],
  education: [
    {
      institution: "University of Washington",
      degree: "Bachelor of Science in Computer Science & Systems",
      date: "June 2017",
      coursework:
        "Data Structures & Algorithms; Compilers; Mobile App Development; Advanced Programming Principles in Java, Python, C, Prolog, and R; Computational Photography; Artificial Intelligence & Machine Learning",
    },
    {
      institution: "Fullstack Open Course, University of Helsinki",
      degree: "Certificate of Completion", // Assuming a certificate for the course
      date: "2022-2024",
      githubRepo: {
        text: "GitHub Repo",
        url: "https://github.com/tstinebaugh/fullstackopencoursework",
      },
      description: [
        "Learned the MERN stack (MongoDB, Express.js, React, Next.js) to create Progressive Web Apps (PWAs) and Single Page Apps (SPAs)",
        "Also learned Jest, Mocha, Cypress, Redux, GraphQL, and React Native.",
        "Gained additional insight into Typescript, node.js, HTML, CSS, CI/CD, and relational databases",
      ],
    },
  ],
  technicalSkills: {
    category: "Technical Skills",
    skills: [
      "Golang",
      "Typescript",
      "Python",
      "React",
      "SQL",
      "PostgreSQL",
      "AWS (EC2, RDS, Lambda, S3, SQS, etc.)",
    ],
  },
  softSkills: {
    category: "Soft Skills",
    skills: [
      "Cross-Functional Collaboration",
      "Communication Across Distributed Teams",
      "Problem Solving",
      "Time Management",
      "Leadership",
      "Growth Mindset",
    ],
  },
  languages: [
    { name: "English", proficiency: "Native Proficiency" },
    { name: "Japanese", proficiency: "JLPT N4 (currently studying toward N3)" },
  ],
  certifications: [
    { name: "CompTIA A+" },
    { name: "TestOut PC Pro" },
    { name: "TestOut Network Pro" },
  ],
};